#ifndef __MAPNIK_VECTOR_TILE_CONFIG_H__
#define __MAPNIK_VECTOR_TILE_CONFIG_H__

#if !defined(MAPNIK_VECTOR_TILE_LIBRARY)
#define MAPNIK_VECTOR_INLINE inline
#else
#define MAPNIK_VECTOR_INLINE
#endif

#define LAYER_ENCODING 3
#define LAYER_NAME_ENCODING 1
#define LAYER_EXTENT_ENCODING 5
#define LAYER_VERSION_ENCODING 15

#define FEATURE_ENCODING 2
#define FEATURE_ID_ENCODING 1
#define FEATURE_TAGS_ENCODING 2
#define FEATURE_TYPE_ENCODING 3
#define FEATURE_GEOMETRY_ENCODING 4
#define FEATURE_RASTER_ENCODING 5

#define KEYS_ENCODING 3
#define VALUE_ENCODING 4
#define VALUE_STRING_ENCODING 1
#define VALUE_FLOAT_ENCODING 2
#define VALUE_DOUBLE_ENCODING 3
#define VALUE_INT_ENCODING 4
#define VALUE_UINT_ENCODING 5
#define VALUE_SINT_ENCODING 6
#define VALUE_BOOL_ENCODING 7

#endif // __MAPNIK_VECTOR_TILE_CONFIG_H__
